("Using web URLs in your username without prior permission from Rubica")
("Save, destroy or deface content on Rubika, including but not limited to user profiles and their images;")
("access to Rubika's exclusive API by a tool other than the Rubika application itself;")
("modify, clone or hack Rubik's; altering other websites and making them appear similar to Rubika in such a way that they falsely appear to be related to Rubika;")
("Publish sexual content (porn) and any illegal content on channels, bots, live broadcasts (lives), Rubino's social network and other parts that are visible to the public;")
("threaten, intimidate, abuse and harass Rubika users or introduce yourself to them elsewhere; Using Rubika services for unauthorized and illegal purposes;")
("Posting violent content on channels, bots, live broadcasts, Rubino's social network and other publicly visible areas;")
("Sending junk mail, inappropriate emails and comments (spam) or scamming Rubika users.")
("Violation of Islamic, moral, customary and any laws of the Islamic Republic of Iran (including but not limited to copyright laws);")
("Sending any type of virus or any type of code that is malicious in nature;")
