("Commercial distribution of audiovisual works without the permission of the Ministry of Culture and Islamic Guidance")
("Introduction of unauthorized audiovisual works instead of authorized works")
("Publishing and serving computer games with criminal content")
("Dissemination of filter breakers and training on how to pass through filtering systems")
("Conducting any criminal computer business and economic activities such as pyramid companies")
("Criminal content related to audiovisual and intellectual property")
("Propaganda against the system of the Islamic Republic of Iran")
("Disrupting national unity and creating differences between the sections of the society, especially through raising racial and ethnic issues")
("Inciting or seducing people to fight and kill each other.Training and facilitation of other computer crimes")
