("Publication of content against the principles of the Constitution")
("Content that harms the Islamic Republic of Iran")
("Any bomb threats")
("Formation of crowd, group, group in cyberspace with the aim of disrupting the country's security")
("Content against public safety and comfort")
("Insulting the Supreme Leader (Imam Khamenei)")
("Insulting any of the great prophets or imams (a.s.) or Hazrat Siddiqa Tahira (p.a.)")
("Quoting material from publications and media and internal and external parties and groups that are deviant and opposed to Islam in such a way that the propaganda is from them.Insulting Imam Khomeini (RA) and distorting his works")
("Propaganda for the benefit of the perverted group or sect and against Islam")
